### ISSUE TITLE
[BUG] Repair Armour macro does not work with Archives 3 armour

### ISSUE THREAD

**Issue by TheFirst05** [Forien/foundryvtt-forien-armoury#51]
When wearing armour from Archives 3, I get the following bug:

Uncaught (in promise) TypeError: Cannot read properties of null (reading '0')
[Detected 1 package: forien-armoury(3.4.0)]
    at #getMaxDamage (ItemRepair.mjs:165:50)
    at ItemRepair.checkTrappingDamage (ItemRepair.mjs:187:39)
    at ItemRepair.mjs:296:30
    at Array.forEach (<anonymous>)
    at ItemRepair.processTrappings (ItemRepair.mjs:292:11)
    at ItemRepair.processWeapons (ItemRepair.mjs:278:17)
    at ItemRepair.checkInventoryForDamage (ItemRepair.mjs:375:35)
    at Macro.eval (eval at #executeScript (foundry.js:20082:16), <anonymous>:6:7)
    at #executeScript (foundry.js:20087:17)
    at Macro.execute (foundry.js:20028:35)
    at #onExecute (foundry.js:79391:17)

All modules are up to date (archives, library, system, armoury).

**Comment by Forien** [comment]
While Armour from Archives 3 is not handled by the macro (and I will add it in the next update), this error is not about Armour. 

I know that because error log contains methods `processWeapons ` and `processTrappings` instead of  `processArmour`; and also `checkTrappingDamage` instead of `checkArmourDamage`.

The culprit is some kind of weapon. If you could contact me on discord and send me JSON of exported Actor that causes the error, I would appreciate it.

**Comment by TheFirst05** [comment]
Ah, sorry about that. I've worked out the offending item: the incendiary thrown item (from core) was causing the problem. Removing the item from the sheet solved the issue.

**Comment by Forien** [comment]
> Ah, sorry about that. I've worked out the offending item: the incendiary thrown item (from core) was causing the problem. Removing the item from the sheet solved the issue.

Ok, thanks. I was able to reproduce and fix the issue. What's funny is that it's not even possible to damage weapons that do not have integer Damage. So a weapon of `SB` damage and `Durable 3` cannot be damaged because of an error 
![image](https://github.com/user-attachments/assets/9b12e7f7-afd3-4f7d-a8a2-21a71c3bfd2d)

Aaanyway, regarding the issue with macro, I've developed a fix, will release a patch soon
